### ISSUE TITLE
Reconciliation Test Bench POST

### ISSUE THREAD

**Issue by saumier** [culturecreates/testbench#1]
@dev-aravind Commented that the Reconciliation API spec only accepts POST requests but the test bench is currently using GET.  I proposed to the Reconciliation CG that we update the [Test bench](https://github.com/reconciliation-api/testbench) and they agreed. 

[Reconciliation CG April 2024 meeting notes](https://etherpad.lobid.org/p/reconciliation-april-2024):  
> - Does the group agree on issue https://github.com/reconciliation-api/testbench/issues/64 to update testbench to use POST? If so I can work on this.
Yes, and that would be great!

**Comment by saumier** [comment]
@AbhishekPAnil I propose you make your changes in this forked repo. It is synched with the original testbench. It also deploys on one of our Github pages for testing https://culturecreates.github.io/testbench/. Then we can submit the contribution.

**Comment by saumier** [comment]
@AbhishekPAnil Your code changes look good, but I am having trouble running the tests (the existing ones) and I am not sure which version of node I should be using. Which version of node did you use and did the existing tests pass?

**Comment by AbhishekPAnil** [comment]
> @AbhishekPAnil Your code changes look good, but I am having trouble running the tests (the existing ones) and I am not sure which version of node I should be using. Which version of node did you use and did the existing tests pass?
> 
> 

Can you try it with node 15.That is mentioned in the workflows.For me it worked with 14 as well.
