### ISSUE TITLE
Add multi-lingual support

### ISSUE THREAD

**Issue by saumier** [culturecreates/testbench#4]
As a user of the test bench, I would like to test my new endpoint running v0.3 of the draft reconciliation service that supports multi-lingual entity names.  

The test bench must continue to work with v0.2 of the reconciliation service according to the published spec so I can continue to work with all the existing endpoints.

Related to https://github.com/culturecreates/artsdata-reconciliation/issues/13

**Comment by saumier** [comment]
@AbhishekPAnil Please make a PR and merge your branch issue-13 into main. Thx

**Comment by AbhishekPAnil** [comment]
>  Moving forward I suggest we also do PRs to the upstream repo in reconciliation group using our main branch.
 
 Yes we can do that in the future.
