### ISSUE TITLE
Detect v1.0-draft

### ISSUE THREAD

**Issue by saumier** [culturecreates/testbench#6]
Please detect the version `v1.0-draft` for testing against the draft spec that we are collaborating on, instead of v0.3.  

Please synch with recent updates from the source and re-open the PR https://github.com/reconciliation-api/testbench/pull/74 from our main branch.

Related issue in Reconciliation Server: https://github.com/culturecreates/artsdata-reconciliation/issues/16

**Comment by saumier** [comment]
@AbhishekPAnil Can you check why this is not working for me? Is it a problem with the Artsdata Reconciliation service, or the test bench?

<img width="1064" alt="Screenshot 2024-09-29 at 10 30 27 PM" src="https://github.com/user-attachments/assets/3fc7521d-29c8-4ad1-90e7-680c7d3b0a52">

**Comment by AbhishekPAnil** [comment]
> @AbhishekPAnil Can you check why this is not working for me? Is it a problem with the Artsdata Reconciliation service, or the test bench? Perhaps the test bench needs to be deployed to our github page.
> 
> <img alt="Screenshot 2024-09-29 at 10 30 27 PM" width="1064" src="https://private-user-images.githubusercontent.com/419491/371925074-3fc7521d-29c8-4ad1-90e7-680c7d3b0a52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2ODAwMzMsIm5iZiI6MTcyNzY3OTczMywicGF0aCI6Ii80MTk0OTEvMzcxOTI1MDc0LTNmYzc1MjFkLTI5YzgtNGFkMS05MGU3LTY4MGM3ZDNiMGE1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQwNzAyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzkxY2MzYTlmYzI3YjU3ODRmZjc5M2M0MTkzY2UzZGNiMDdiZDE1ZmUyMzcwN2EyM2FhY2EyNWVlNTcyNDlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Dt1iRjJ-DM5QgZgULyOLZ8iocmtmad7ESAfYThIEONs">

You are right.It needs to deployed after the merge.I have deployed .Please check again.
If you face any ssl issue from BE,please open this link https://35.183.160.6/api and try again in the test bench.Thanks!.
